# Generated by Django 3.1.7 on 2021-04-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=150)),
                ('translation', models.CharField(max_length=150)),
                ('another_translations', models.CharField(max_length=150)),
                ('definition', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Термин',
                'verbose_name_plural': 'Термины',
            },
        ),
    ]
