# Generated by Django 3.1.7 on 2021-04-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translations',
            name='another_translations',
            field=models.CharField(max_length=150, verbose_name='Другие варианты перевода'),
        ),
        migrations.AlterField(
            model_name='translations',
            name='definition',
            field=models.TextField(blank=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='translations',
            name='term',
            field=models.CharField(max_length=150, verbose_name='Термин'),
        ),
        migrations.AlterField(
            model_name='translations',
            name='translation',
            field=models.CharField(max_length=150, verbose_name='Перевод'),
        ),
    ]
